### ISSUE TITLE
TodoController定位不明确

### ISSUE THREAD

**Issue by yichaosun** [bravekingzhang/flutter_template#3]
用TodoController来维护Page，侧重页面
用TodoService来维护todo相关业务逻辑，包含对Repository的存取。
这样你在TodoItem中需要的是TodoService，而不是去获取TodoController

**Comment by bravekingzhang** [comment]
**talk is cheap ,show me your pr**

**Comment by bravekingzhang** [comment]
@yichaosun 辛苦大佬，缕缕思路，提交pr，or给下伪代码，我们来把这个模板整理得强大一些，方便更多的人无痛入坑flutter
