### ISSUE TITLE
支持web的话最好加上web也能用的Platform class

### ISSUE THREAD

**Issue by Dabbit-Chan** [bravekingzhang/flutter_template#4]
毕竟web是用不了Platform.is***这一套判断方法的，多端项目也不可避免地要使用一些判断平台的方法来做业务。
比如这样：
![image](https://github.com/bravekingzhang/flutter_template/assets/25811834/80b586e5-14ab-4b87-99cb-5b508c5916fd)

**Comment by bravekingzhang** [comment]
这个很奈斯！

**Comment by bravekingzhang** [comment]
<img width="625" alt="image" src="https://github.com/bravekingzhang/flutter_template/assets/4476322/328dcd4b-fba5-4db7-8ad4-cc608bf5ea24">
get 框架自带这些，因此这个可以关闭了
